import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import { AudioLines, BarChart3, Check, ClipboardCheck, CloudUpload, Eye, EyeOff, FileAudio, FileDown, FileText, Globe2, LogOut, MessageSquareQuote, Play, RefreshCw, Settings2, Sparkles, Trash2, UserRound, AlertTriangle } from 'lucide-react';
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Label, Select, Separator } from './components/ui';
import { MultiSelect } from './components/multi-select';
import { SingleSelect } from './components/single-select';
import './index.css';

const copy = {
  en: {
    signIn: 'Welcome back', signInDescription: 'Sign in to continue to your call quality workspace.', email: 'Email', password: 'Password', showPassword: 'Show password', hidePassword: 'Hide password', login: 'Sign in', signingIn: 'Signing in…', logout: 'Log out',
    provider: 'AI provider', gemini: 'Google Gemini', openai: 'OpenAI', category: 'Category', subCategory: 'Sub-category', chooseCategory: 'Choose categories (optional)', chooseSubCategory: 'Choose sub-categories (optional)', searchCategory: 'Search categories…', searchSubCategory: 'Search sub-categories…', noResults: 'No results found.', selectedCount: '{count} selected', clearSelections: 'Clear selections', loadingSetup: 'Loading sheet setup…', configurationError: 'The sheet setup could not be loaded.',
    recordings: 'Call recordings', drop: 'Drop audio files here or browse', supported: 'MP3, WAV, M4A, AAC, OGG', analyze: 'Run', analyzing: 'Analyzing…', mode: 'Analysis mode', qaMode: 'QA audit & scorecard', voiceMode: 'Customer voice & objections', coachingMode: 'Advisor pitch & coaching',
    report: 'Audit report', downloadPdf: 'PDF', downloadWord: 'Word', copy: 'Copy', cached: 'Cached result', fresh: 'Fresh AI result', noFiles: 'Please upload at least one audio recording.', noProvider: 'Your account has no key for this provider.', noParameter: 'Choose a QA parameter.', serverError: 'Something went wrong. Please try again.', loginError: 'Invalid email or password.', networkAccessError: 'This network address is not allowed.', unavailable: 'The authentication service is unavailable.',
    companyFallback: 'QA Auditor', remove: 'Remove', pageTitle: 'Review a customer call', setup: 'Audit setup', fileReady: 'ready', unsupported: 'Choose a supported audio file.', duplicate: 'That recording is already in the list.', copyUnavailable: 'Copy is unavailable in this browser.', parameter: 'QA parameter', chooseParameter: 'Choose a parameter', searchParameter: 'Search parameters…', saveDefault: 'Save as default', defaultSaved: 'Default saved', temporary: 'Active for this session', unsavedWarning: 'Results were generated but were not saved to Google Sheets.', failedCall: 'Call failed', summary: 'Run summary'
  },
  bn: {
    signIn: 'আবার স্বাগতম', signInDescription: 'কল কোয়ালিটি ওয়ার্কস্পেসে যেতে লগইন করুন।', email: 'ইমেইল', password: 'পাসওয়ার্ড', showPassword: 'পাসওয়ার্ড দেখান', hidePassword: 'পাসওয়ার্ড লুকান', login: 'লগইন', signingIn: 'যাচাই হচ্ছে…', logout: 'লগআউট',
    provider: 'AI প্রোভাইডার', gemini: 'Google Gemini', openai: 'OpenAI', category: 'ক্যাটাগরি', subCategory: 'সাব-ক্যাটাগরি', chooseCategory: 'ক্যাটাগরি বেছে নিন (ঐচ্ছিক)', chooseSubCategory: 'সাব-ক্যাটাগরি বেছে নিন (ঐচ্ছিক)', searchCategory: 'ক্যাটাগরি খুঁজুন…', searchSubCategory: 'সাব-ক্যাটাগরি খুঁজুন…', noResults: 'কোনো ফল পাওয়া যায়নি।', selectedCount: '{count}টি নির্বাচিত', clearSelections: 'নির্বাচন মুছুন', loadingSetup: 'শিট সেটআপ লোড হচ্ছে…', configurationError: 'শিট সেটআপ লোড করা যায়নি।',
    recordings: 'কল রেকর্ডিং', drop: 'এখানে অডিও ফেলুন অথবা ব্রাউজ করুন', supported: 'MP3, WAV, M4A, AAC, OGG', analyze: 'Run', analyzing: 'বিশ্লেষণ হচ্ছে…', mode: 'বিশ্লেষণের ধরন', qaMode: 'QA অডিট ও স্কোরকার্ড', voiceMode: 'কাস্টমার ভয়েস ও আপত্তি', coachingMode: 'এডভাইসর পিচ ও কোচিং',
    report: 'অডিট রিপোর্ট', downloadPdf: 'PDF', downloadWord: 'Word', copy: 'কপি', cached: 'ক্যাশড ফলাফল', fresh: 'নতুন AI ফলাফল', noFiles: 'কমপক্ষে একটি অডিও রেকর্ডিং আপলোড করুন।', noProvider: 'এই প্রোভাইডারের জন্য কোনো key নেই।', noParameter: 'একটি QA প্যারামিটার বেছে নিন।', serverError: 'সমস্যা হয়েছে। আবার চেষ্টা করুন।', loginError: 'ইমেইল বা পাসওয়ার্ড সঠিক নয়।', networkAccessError: 'এই নেটওয়ার্ক ঠিকানাটি অনুমোদিত নয়।', unavailable: 'অথেন্টিকেশন সার্ভিস এখন unavailable।',
    companyFallback: 'QA Auditor', remove: 'মুছুন', pageTitle: 'কাস্টমার কল রিভিউ করুন', setup: 'অডিট সেটআপ', fileReady: 'প্রস্তুত', unsupported: 'সমর্থিত অডিও ফাইল বেছে নিন।', duplicate: 'এই রেকর্ডিংটি ইতিমধ্যে তালিকায় আছে।', copyUnavailable: 'এই ব্রাউজারে কপি করা যাচ্ছে না।', parameter: 'QA প্যারামিটার', chooseParameter: 'প্যারামিটার বেছে নিন', searchParameter: 'প্যারামিটার খুঁজুন…', saveDefault: 'ডিফল্ট হিসেবে সেভ করুন', defaultSaved: 'ডিফল্ট সেভ হয়েছে', temporary: 'এই সেশনের জন্য সক্রিয়', unsavedWarning: 'রিপোর্ট তৈরি হয়েছে, কিন্তু Google Sheets-এ সেভ হয়নি।', failedCall: 'কল ব্যর্থ', summary: 'রান সামারি'
  }
};

function formatBytes(bytes) { return `${(bytes / (1024 * 1024)).toFixed(2)} MB`; }
function renderMarkdown(markdown) { return DOMPurify.sanitize(marked.parse(markdown || '')); }

function App() {
  const [language, setLanguage] = useState(() => localStorage.getItem('qa-language') || 'en');
  const [user, setUser] = useState(null); const [loginState, setLoginState] = useState({ loading: true, error: '' });
  const [provider, setProvider] = useState('gemini'); const [auditConfig, setAuditConfig] = useState({ products: [], parameters: [], savedDefaultParameter: '', activeParameter: '' });
  const [configState, setConfigState] = useState({ loading: false, error: '' }); const [parameter, setParameter] = useState('');
  const [selectedCategories, setSelectedCategories] = useState([]); const [selectedSubCategoryIds, setSelectedSubCategoryIds] = useState([]);
  const [mode, setMode] = useState('single'); const [files, setFiles] = useState([]); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [status, setStatus] = useState('');
  const [loginForm, setLoginForm] = useState({ email: '', password: '' }); const [dragActive, setDragActive] = useState(false);
  const inputRef = useRef(null); const reportRef = useRef(null); const reportCardRef = useRef(null); const runRef = useRef(0); const t = copy[language];

  useEffect(() => { localStorage.setItem('qa-language', language); document.documentElement.lang = language === 'bn' ? 'bn' : 'en'; }, [language]);
  useEffect(() => { checkSession(); }, []);
  useEffect(() => { if (user) loadAuditConfiguration(); }, [user]);
  useEffect(() => { if (result) requestAnimationFrame(() => reportCardRef.current?.focus()); }, [result]);

  const providers = user?.providers || []; const companyName = user?.companyName || t.companyFallback;
  const categoryOptions = useMemo(() => auditConfig.products.map(item => item.category), [auditConfig.products]);
  const subCategoryOptions = useMemo(() => auditConfig.products.filter(item => selectedCategories.includes(item.category)).flatMap(item => item.subCategories.map(subCategory => ({ value: JSON.stringify([item.category, subCategory]), label: subCategory, description: item.category, category: item.category, subCategory }))), [auditConfig.products, selectedCategories]);
  const productSelections = useMemo(() => selectedSubCategoryIds.map(id => subCategoryOptions.find(option => option.value === id)).filter(Boolean).map(option => ({ category: option.category, subCategory: option.subCategory })), [selectedSubCategoryIds, subCategoryOptions]);
  const previewUrls = useMemo(() => files.map(file => ({ file, url: URL.createObjectURL(file) })), [files]);
  useEffect(() => () => previewUrls.forEach(item => URL.revokeObjectURL(item.url)), [previewUrls]);

  async function checkSession() { try { const response = await fetch('/api/session', { credentials: 'same-origin' }); if (response.ok) { const data = await response.json(); setUser(data.user); setProvider(data.user.providers[0] || 'gemini'); } } catch {} setLoginState(state => ({ ...state, loading: false })); }
  async function handleLogin(event) { event.preventDefault(); setLoginState({ loading: true, error: '' }); try { const response = await fetch('/api/login', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(loginForm) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(response.status === 403 ? t.networkAccessError : response.status === 503 ? t.unavailable : t.loginError); setUser(data.user); setProvider(data.user.providers[0] || 'gemini'); setLoginForm({ email: '', password: '' }); setLoginState({ loading: false, error: '' }); } catch (error) { setLoginState({ loading: false, error: error.message }); } }
  async function loadAuditConfiguration() { setConfigState({ loading: true, error: '' }); try { const response = await fetch('/api/audit-config', { credentials: 'same-origin' }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || t.configurationError); const next = { products: Array.isArray(data.products) ? data.products : [], parameters: Array.isArray(data.parameters) ? data.parameters : [], savedDefaultParameter: String(data.savedDefaultParameter || ''), activeParameter: String(data.activeParameter || '') }; setAuditConfig(next); setParameter(next.activeParameter); setSelectedCategories([]); setSelectedSubCategoryIds([]); setConfigState({ loading: false, error: '' }); } catch (error) { setConfigState({ loading: false, error: error.message || t.configurationError }); } }
  async function changeParameter(value) { setParameter(value); setAuditConfig(current => ({ ...current, activeParameter: value })); setStatus(''); try { const response = await fetch('/api/session/parameter', { method: 'PUT', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ parameter: value }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || t.serverError); } catch (error) { setStatus(error.message); loadAuditConfiguration(); } }
  async function saveDefault() { try { const response = await fetch('/api/user/default-parameter', { method: 'PUT', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ parameter }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || t.serverError); setAuditConfig(current => ({ ...current, savedDefaultParameter: data.savedDefaultParameter, activeParameter: data.activeParameter })); setStatus(t.defaultSaved); } catch (error) { setStatus(error.message); } }
  async function logout() { runRef.current += 1; await fetch('/api/logout', { method: 'POST', credentials: 'same-origin' }).catch(() => {}); setUser(null); setFiles([]); setResult(null); setParameter(''); setAuditConfig({ products: [], parameters: [], savedDefaultParameter: '', activeParameter: '' }); setSelectedCategories([]); setSelectedSubCategoryIds([]); }
  function addFiles(incoming) { setFiles(current => { const next = [...current]; for (const file of incoming) { const supported = file.type.startsWith('audio/') || /\.(mp3|wav|m4a|aac|ogg)$/i.test(file.name); if (!supported) { setStatus(t.unsupported); continue; } if (next.some(item => item.name === file.name && item.size === file.size)) { setStatus(t.duplicate); continue; } next.push(file); setStatus(''); } return next; }); }
  function removeFile(index) { setFiles(current => current.filter((_, itemIndex) => itemIndex !== index)); }

  async function analyze() {
    if (!files.length) return setStatus(t.noFiles); if (!providers.includes(provider)) return setStatus(t.noProvider); if (mode !== 'voice' && !parameter) return setStatus(t.noParameter);
    const runId = ++runRef.current; setBusy(true); setStatus(t.analyzing); setResult(null);
    try { const audioFiles = []; for (let index = 0; index < files.length; index += 1) { setStatus(`${t.analyzing} ${index + 1}/${files.length}`); audioFiles.push({ name: files[index].name, mimeType: files[index].type || 'audio/mp3', data: await toBase64(files[index]) }); }
      const response = await fetch('/api/analyze', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ provider, mode, parameter, categories: selectedCategories, productSelections, audioFiles }) }); const data = await response.json().catch(() => ({})); if (runId !== runRef.current) return; if (response.status === 401) { await logout(); throw new Error(t.loginError); } if (Array.isArray(data.items)) setResult(data); if (!response.ok) throw new Error(data.error || t.serverError); setResult(data); setStatus('');
    } catch (error) { if (runId === runRef.current) setStatus(error.message || t.serverError); } finally { if (runId === runRef.current) setBusy(false); }
  }

  function exportPdf() { window.print(); }
  function exportWord() { if (!reportRef.current) return; const html = `<html><head><meta charset="utf-8"><title>QA Report</title><style>body{font-family:Arial}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccc;padding:8px}</style></head><body>${reportRef.current.innerHTML}</body></html>`; const link = document.createElement('a'); link.href = `data:application/msword;charset=utf-8,${encodeURIComponent(html)}`; link.download = `QA_Audit_${new Date().toISOString().slice(0, 10)}.doc`; link.click(); }
  async function copyReport() { if (!navigator.clipboard) return setStatus(t.copyUnavailable); await navigator.clipboard.writeText(result?.report || ''); setStatus(language === 'en' ? 'Report copied.' : 'রিপোর্ট কপি হয়েছে।'); }
  function toggleLanguage() { setLanguage(current => current === 'en' ? 'bn' : 'en'); }

  if (loginState.loading) return <div className="loading-screen"><Sparkles size={22} /> Loading QA Auditor…</div>;
  if (!user) return <LoginScreen t={t} language={language} toggleLanguage={toggleLanguage} loginForm={loginForm} setLoginForm={setLoginForm} onSubmit={handleLogin} state={loginState} />;
  return <div className="app-shell" id="top">
    <header className="topbar"><div className="topbar-inner"><div className="brand-lockup"><div className="brand-mark"><AudioLines size={21} /></div><div><strong>{companyName}</strong><span>QA Auditor</span></div></div><div className="topbar-actions"><LanguageToggle language={language} onClick={toggleLanguage} /><div className="account-chip"><div className="avatar"><UserRound size={16} /></div><div><strong>{user.name || user.email.split('@')[0]}</strong><span>{user.email}</span></div></div><Button variant="ghost" size="icon" onClick={logout} aria-label={t.logout}><LogOut size={18} /></Button></div></div></header>
    <main className="main-area"><div className="page-container"><div className="page-heading"><h1>{t.pageTitle}</h1></div><div className="audit-layout">
      <section className="flow-panel"><div className="section-heading"><div className="section-icon"><CloudUpload size={19} /></div><h2>{t.recordings}</h2></div>
        <button type="button" className={`dropzone ${dragActive ? 'drag-active' : ''} ${files.length ? 'compact' : ''}`} onClick={() => inputRef.current?.click()} onDragEnter={event => { event.preventDefault(); setDragActive(true); }} onDragOver={event => event.preventDefault()} onDragLeave={() => setDragActive(false)} onDrop={event => { event.preventDefault(); setDragActive(false); addFiles(Array.from(event.dataTransfer.files)); }} disabled={busy}><div className="upload-icon"><CloudUpload size={25} /></div><div><strong>{t.drop}</strong><span>{t.supported}</span></div></button>
        <input ref={inputRef} type="file" accept="audio/*" multiple hidden onChange={event => addFiles(Array.from(event.target.files || []))} />
        {files.length > 0 && <div className="file-list">{previewUrls.map(({ file, url }, index) => <div className="file-row" key={`${file.name}-${file.size}`}><div className="file-type"><FileAudio size={17} /></div><div className="file-meta"><strong>{file.name}</strong><span>{formatBytes(file.size)} · {t.fileReady}</span></div><Button variant="ghost" size="icon" onClick={() => removeFile(index)} aria-label={`${t.remove} ${file.name}`} disabled={busy}><Trash2 size={16} /></Button><audio controls src={url} preload="metadata" /></div>)}</div>}
        <div className="mode-section"><div className="inline-heading"><h2>{t.mode}</h2></div><div className="mode-grid" role="radiogroup">{[['single', ClipboardCheck, t.qaMode], ['voice', MessageSquareQuote, t.voiceMode], ['coaching', BarChart3, t.coachingMode]].map(([value, Icon, label]) => <button type="button" role="radio" aria-checked={mode === value} className={`mode-card ${mode === value ? 'selected' : ''}`} key={value} onClick={() => setMode(value)} disabled={busy}><Icon size={19} /><span>{label}</span>{mode === value && <Check size={16} />}</button>)}</div></div>
        <div className="run-action"><Button className="analyze-button" size="lg" onClick={analyze} disabled={busy || !files.length || (mode !== 'voice' && !parameter)}>{busy ? <RefreshCw className="spin" size={18} /> : <Play size={18} />}{busy ? t.analyzing : t.analyze}</Button></div><div className={`status-message ${busy ? 'processing' : ''}`} role="status">{status}</div>
      </section>
      <aside className="setup-panel"><div className="section-heading"><div className="section-icon subtle"><Settings2 size={18} /></div><h2>{t.setup}</h2></div><div className="setup-fields">
        {providers.length > 1 ? <div><Label htmlFor="provider">{t.provider}</Label><Select id="provider" value={provider} onChange={event => setProvider(event.target.value)} disabled={busy}>{providers.includes('gemini') && <option value="gemini">{t.gemini}</option>}{providers.includes('openai') && <option value="openai">{t.openai}</option>}</Select></div> : <div className="provider-summary"><span>{t.provider}</span><strong>{provider === 'gemini' ? t.gemini : t.openai}</strong></div>}
        {mode !== 'voice' && <div className="parameter-field"><Label htmlFor="qa-parameter">{t.parameter}</Label><SingleSelect id="qa-parameter" value={parameter} options={auditConfig.parameters} placeholder={t.chooseParameter} searchPlaceholder={t.searchParameter} emptyText={t.noResults} disabled={busy || configState.loading} onChange={changeParameter} /><div className="field-footer"><span>{parameter === auditConfig.savedDefaultParameter ? t.defaultSaved : t.temporary}</span>{parameter && parameter !== auditConfig.savedDefaultParameter && <Button variant="link" size="sm" onClick={saveDefault} disabled={busy}>{t.saveDefault}</Button>}</div></div>}
        <div className="product-fields"><div><Label htmlFor="product-category">{t.category}</Label><MultiSelect id="product-category" value={selectedCategories} options={categoryOptions} placeholder={t.chooseCategory} searchPlaceholder={t.searchCategory} emptyText={t.noResults} selectedText={t.selectedCount} clearText={t.clearSelections} disabled={busy || configState.loading} onChange={values => { setSelectedCategories(values); setSelectedSubCategoryIds(current => current.filter(id => { try { return values.includes(JSON.parse(id)[0]); } catch { return false; } })); }} /></div><div><Label htmlFor="product-sub-category">{t.subCategory}</Label><MultiSelect id="product-sub-category" value={selectedSubCategoryIds} options={subCategoryOptions} placeholder={t.chooseSubCategory} searchPlaceholder={t.searchSubCategory} emptyText={t.noResults} selectedText={t.selectedCount} clearText={t.clearSelections} disabled={busy || configState.loading || !selectedCategories.length} onChange={setSelectedSubCategoryIds} /></div>{configState.loading && <div className="field-state">{t.loadingSetup}</div>}{configState.error && <div className="error-message">{configState.error}</div>}</div>
      </div></aside>
    </div>
    {result && <section ref={reportCardRef} className="result-section" tabIndex="-1"><div className="report-toolbar"><div><div className="result-kicker"><Check size={14} /> {result.cached ? t.cached : t.fresh}</div><h2><FileText size={19} /> {t.report}</h2></div><div className="report-actions"><Button variant="outline" size="sm" onClick={exportPdf}><FileDown size={15} /> {t.downloadPdf}</Button><Button variant="outline" size="sm" onClick={exportWord}><FileText size={15} /> {t.downloadWord}</Button><Button variant="outline" size="sm" onClick={copyReport}><Check size={15} /> {t.copy}</Button></div></div>
      {result.auditResultWrite?.status === 'failed' && <div className="storage-warning"><AlertTriangle size={18} /><strong>{result.auditResultWrite.message || t.unsavedWarning}</strong></div>}
      <div ref={reportRef} className="result-items">{result.items?.map((item, index) => item.status === 'success' ? <Card className="report-card" key={`${item.kind}-${item.fileName || index}`}><CardHeader><CardTitle>{item.kind === 'summary' ? t.summary : item.fileName || t.report}{item.kind === 'call' && <span className={`score-pill ${item.ce ? 'ce' : ''}`}>{item.score}/{item.maximum}</span>}</CardTitle></CardHeader><CardContent><div className="report-content" dangerouslySetInnerHTML={{ __html: renderMarkdown(item.markdown) }} /></CardContent></Card> : <Card className="report-card failed-result" key={`${item.kind}-${item.fileName || index}`}><CardContent><AlertTriangle size={20} /><div><strong>{item.fileName || t.summary}: {t.failedCall}</strong><p>{item.error}</p></div></CardContent></Card>)}</div>
    </section>}
    </div></main>
  </div>;
}

function LoginScreen({ t, language, toggleLanguage, loginForm, setLoginForm, onSubmit, state }) { const [showPassword, setShowPassword] = useState(false); return <div className="login-shell"><Card className="login-card"><div className="login-brand"><strong>QA Auditor</strong><LanguageToggle language={language} onClick={toggleLanguage} /></div><Separator /><CardHeader><CardTitle>{t.signIn}</CardTitle><CardDescription>{t.signInDescription}</CardDescription></CardHeader><CardContent><form onSubmit={onSubmit} className="login-form"><Label htmlFor="email">{t.email}</Label><Input id="email" type="email" autoComplete="username" required value={loginForm.email} onChange={event => setLoginForm({ ...loginForm, email: event.target.value })} /><Label htmlFor="password">{t.password}</Label><div className="password-field"><Input id="password" type={showPassword ? 'text' : 'password'} autoComplete="current-password" required value={loginForm.password} onChange={event => setLoginForm({ ...loginForm, password: event.target.value })} /><button type="button" className="password-toggle" onClick={() => setShowPassword(current => !current)} aria-label={showPassword ? t.hidePassword : t.showPassword}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div>{state.error && <div className="error-message" role="alert">{state.error}</div>}<Button type="submit" size="lg" disabled={state.loading}>{state.loading ? t.signingIn : t.login}</Button></form></CardContent></Card></div>; }
function LanguageToggle({ language, onClick }) { return <Button variant="outline" size="sm" onClick={onClick}><Globe2 size={15} /> {language === 'en' ? 'বাংলা' : 'English'}</Button>; }
function toBase64(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); }); }

createRoot(document.getElementById('root')).render(<App />);
